[package]
name = "circle"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.1.3"
env_logger = "0.10.1"
winit = "0.29.6"


[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
